//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiled2agb.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tiled2agb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die border_block_map ähnelt.
        /// </summary>
        internal static string STR_BORDER_MAP_FILE {
            get {
                return ResourceManager.GetString("STR_BORDER_MAP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die collision_data ähnelt.
        /// </summary>
        internal static string STR_COL_DATA {
            get {
                return ResourceManager.GetString("STR_COL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die csv ähnelt.
        /// </summary>
        internal static string STR_ENCODING_CSV {
            get {
                return ResourceManager.GetString("STR_ENCODING_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_battletype ähnelt.
        /// </summary>
        internal static string STR_HEAD_BATTLETYPE {
            get {
                return ResourceManager.GetString("STR_HEAD_BATTLETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_cave ähnelt.
        /// </summary>
        internal static string STR_HEAD_CAVE {
            get {
                return ResourceManager.GetString("STR_HEAD_CAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_index ähnelt.
        /// </summary>
        internal static string STR_HEAD_INDEX {
            get {
                return ResourceManager.GetString("STR_HEAD_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_maptype ähnelt.
        /// </summary>
        internal static string STR_HEAD_MAPTYPE {
            get {
                return ResourceManager.GetString("STR_HEAD_MAPTYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_music ähnelt.
        /// </summary>
        internal static string STR_HEAD_MUSIC {
            get {
                return ResourceManager.GetString("STR_HEAD_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_name ähnelt.
        /// </summary>
        internal static string STR_HEAD_NAME {
            get {
                return ResourceManager.GetString("STR_HEAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_showname ähnelt.
        /// </summary>
        internal static string STR_HEAD_SHOW_NAME {
            get {
                return ResourceManager.GetString("STR_HEAD_SHOW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_unknown ähnelt.
        /// </summary>
        internal static string STR_HEAD_UNKNOWN {
            get {
                return ResourceManager.GetString("STR_HEAD_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_weather ähnelt.
        /// </summary>
        internal static string STR_HEAD_WEATHER {
            get {
                return ResourceManager.GetString("STR_HEAD_WEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tiled2agb:  ähnelt.
        /// </summary>
        internal static string STR_PREFIX_CONSOLE {
            get {
                return ResourceManager.GetString("STR_PREFIX_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die border_layer ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_BORDER {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die collision_layer ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_COLLISION {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_COLLISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die map_layer ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_MAP {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die layer_type ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_NAME {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_NAME", resourceCulture);
            }
        }
    }
}
