//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tiled2agb.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("tiled2agb.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die border_block_map ähnelt.
        /// </summary>
        internal static string STR_BORDER_MAP_FILE {
            get {
                return ResourceManager.GetString("STR_BORDER_MAP_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die collision_data ähnelt.
        /// </summary>
        internal static string STR_COL_DATA {
            get {
                return ResourceManager.GetString("STR_COL_DATA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die csv ähnelt.
        /// </summary>
        internal static string STR_ENCODING_CSV {
            get {
                return ResourceManager.GetString("STR_ENCODING_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die height ähnelt.
        /// </summary>
        internal static string STR_EVT_HEIGHT {
            get {
                return ResourceManager.GetString("STR_EVT_HEIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die field_3 ähnelt.
        /// </summary>
        internal static string STR_EVT_P_F3 {
            get {
                return ResourceManager.GetString("STR_EVT_P_F3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die field_b ähnelt.
        /// </summary>
        internal static string STR_EVT_P_FB {
            get {
                return ResourceManager.GetString("STR_EVT_P_FB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die field_d ähnelt.
        /// </summary>
        internal static string STR_EVT_P_FD {
            get {
                return ResourceManager.GetString("STR_EVT_P_FD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die flag ähnelt.
        /// </summary>
        internal static string STR_EVT_P_FLAG {
            get {
                return ResourceManager.GetString("STR_EVT_P_FLAG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die image ähnelt.
        /// </summary>
        internal static string STR_EVT_P_IMG {
            get {
                return ResourceManager.GetString("STR_EVT_P_IMG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die movement_area ähnelt.
        /// </summary>
        internal static string STR_EVT_P_MOVEMENT {
            get {
                return ResourceManager.GetString("STR_EVT_P_MOVEMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die nr ähnelt.
        /// </summary>
        internal static string STR_EVT_P_NR {
            get {
                return ResourceManager.GetString("STR_EVT_P_NR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die rival ähnelt.
        /// </summary>
        internal static string STR_EVT_P_RIVAL {
            get {
                return ResourceManager.GetString("STR_EVT_P_RIVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die running_behavior ähnelt.
        /// </summary>
        internal static string STR_EVT_P_RUNBEHAV {
            get {
                return ResourceManager.GetString("STR_EVT_P_RUNBEHAV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die sight_distance ähnelt.
        /// </summary>
        internal static string STR_EVT_P_SIGHT {
            get {
                return ResourceManager.GetString("STR_EVT_P_SIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die trainer ähnelt.
        /// </summary>
        internal static string STR_EVT_P_TRAINER {
            get {
                return ResourceManager.GetString("STR_EVT_P_TRAINER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die script_label ähnelt.
        /// </summary>
        internal static string STR_EVT_SCRIPT {
            get {
                return ResourceManager.GetString("STR_EVT_SCRIPT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die evt_type ähnelt.
        /// </summary>
        internal static string STR_EVT_TYPE {
            get {
                return ResourceManager.GetString("STR_EVT_TYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die evt_item ähnelt.
        /// </summary>
        internal static string STR_EVTTYPE_ITEM {
            get {
                return ResourceManager.GetString("STR_EVTTYPE_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die evt_person ähnelt.
        /// </summary>
        internal static string STR_EVTTYPE_PERSON {
            get {
                return ResourceManager.GetString("STR_EVTTYPE_PERSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die evt_sign ähnelt.
        /// </summary>
        internal static string STR_EVTTYPE_SIGN {
            get {
                return ResourceManager.GetString("STR_EVTTYPE_SIGN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die evt_trigger ähnelt.
        /// </summary>
        internal static string STR_EVTTYPE_TRIGGER {
            get {
                return ResourceManager.GetString("STR_EVTTYPE_TRIGGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die evt_warp ähnelt.
        /// </summary>
        internal static string STR_EVTTYPE_WARP {
            get {
                return ResourceManager.GetString("STR_EVTTYPE_WARP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_battletype ähnelt.
        /// </summary>
        internal static string STR_HEAD_BATTLETYPE {
            get {
                return ResourceManager.GetString("STR_HEAD_BATTLETYPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_cave ähnelt.
        /// </summary>
        internal static string STR_HEAD_CAVE {
            get {
                return ResourceManager.GetString("STR_HEAD_CAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_dig ähnelt.
        /// </summary>
        internal static string STR_HEAD_DIG {
            get {
                return ResourceManager.GetString("STR_HEAD_DIG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_escaperope ähnelt.
        /// </summary>
        internal static string STR_HEAD_ESCAPEROPE {
            get {
                return ResourceManager.GetString("STR_HEAD_ESCAPEROPE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_index ähnelt.
        /// </summary>
        internal static string STR_HEAD_INDEX {
            get {
                return ResourceManager.GetString("STR_HEAD_INDEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_light ähnelt.
        /// </summary>
        internal static string STR_HEAD_LIGHT {
            get {
                return ResourceManager.GetString("STR_HEAD_LIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_music ähnelt.
        /// </summary>
        internal static string STR_HEAD_MUSIC {
            get {
                return ResourceManager.GetString("STR_HEAD_MUSIC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_name ähnelt.
        /// </summary>
        internal static string STR_HEAD_NAME {
            get {
                return ResourceManager.GetString("STR_HEAD_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_showname ähnelt.
        /// </summary>
        internal static string STR_HEAD_SHOW_NAME {
            get {
                return ResourceManager.GetString("STR_HEAD_SHOW_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_unknown ähnelt.
        /// </summary>
        internal static string STR_HEAD_UNKNOWN {
            get {
                return ResourceManager.GetString("STR_HEAD_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die header_weather ähnelt.
        /// </summary>
        internal static string STR_HEAD_WEATHER {
            get {
                return ResourceManager.GetString("STR_HEAD_WEATHER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die entity_layer ähnelt.
        /// </summary>
        internal static string STR_OBJLAYER_EVENT {
            get {
                return ResourceManager.GetString("STR_OBJLAYER_EVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die layer_type ähnelt.
        /// </summary>
        internal static string STR_OBJLAYER_NAME {
            get {
                return ResourceManager.GetString("STR_OBJLAYER_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die tiled2agb:  ähnelt.
        /// </summary>
        internal static string STR_PREFIX_CONSOLE {
            get {
                return ResourceManager.GetString("STR_PREFIX_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die border_layer ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_BORDER {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_BORDER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die collision_layer ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_COLLISION {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_COLLISION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die map_layer ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_MAP {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die layer_type ähnelt.
        /// </summary>
        internal static string STR_PROPERTY_LTYPE_NAME {
            get {
                return ResourceManager.GetString("STR_PROPERTY_LTYPE_NAME", resourceCulture);
            }
        }
    }
}
